### ISSUE TITLE
[Feature] User-friendly interface

### ISSUE THREAD

**Issue by vanja-san** [WFCD/navis#113]
### Describe the feature you would like.

`A little pathos...`
I just wanted to show you how convenient it would be if:
- Instead of a pull-out menu, there was a bottom navigation bar
- Instead of tabs, there were page indicators
- And the drop-down menu, always a good idea
- Also suitable design icons and nice-looking cards

### Additional context

<img src="https://user-images.githubusercontent.com/7201687/152494500-c6c7f41a-934c-48fc-8ae5-edf2126d4a2c.png" width="240"> ... <img src="https://user-images.githubusercontent.com/7201687/152495035-f4ac03c7-91d4-4d07-bf02-a284ca26cf23.png" width="240"> ... <img src="https://user-images.githubusercontent.com/7201687/152495206-e5b6df0a-df5d-4f69-bcaf-fce9de318f7e.png" width="240"> ... <img src="https://user-images.githubusercontent.com/7201687/152495344-3dbb2d40-cffb-4f2d-93f4-95ab473b6c8f.png" width="240">

**Comment by SlayerOrnstein** [comment]
First and foremost I'm not a designer so most of the UI/UX was made from what I understood from the material design spec, having said that the design here isn't bad:
- Honestly I'd love to go back to a navigation bar

- indicators would mean more travailing, indicators are meant to show what page you are on, but tabs let you see and skip around pages

- drop downs are always nice, but Simaris targets a feature and would most likely be better down in the navigation bar

- not sure what you mean by "suitable design icons and nice-looking cards"

**Comment by TobiTenno** [comment]
typically menus are for options, not "other links dump section"

**Comment by vanja-san** [comment]
@SlayerOrnstein @TobiTenno
`By way, I apologize for my poor English.` 😅
- I hope so.
- A page change with finger movement should not make it difficult for user to navigate through pages. (Touch Slider)
	- And yes, it's just a sketch, not the final result.
- Here I'm assuming that I'm using gestures on my phone, and pull-out menu isn't very convenient in that case.
	- What if...
		<img src="https://user-images.githubusercontent.com/7201687/152615005-5476f7ed-dac2-40f7-a0f8-2cace5cfd9af.png" width=35%>

- In that case, you can ignore it.

**Comment by vanja-san** [comment]
About the little circle next to name, it's just a marker for logo.

**Comment by SlayerOrnstein** [comment]
> @SlayerOrnstein @TobiTenno `By way, I apologize for my poor English.` 😅
> 
>     * I hope so.
> 
>     * A page change with finger movement should not make it difficult for user to navigate through pages. (Touch Slider)
> 
>     * Here I'm assuming that I'm using gestures on my phone, and pull-out menu isn't very convenient in that case.
>       
>       * What if...
>         <img alt="" width="35%" src="https://user-images.githubusercontent.com/7201687/152615005-5476f7ed-dac2-40f7-a0f8-2cace5cfd9af.png">
> 
>     * In that case, you can ignore it.

That's actually better, can probably put Simaris target data under there too.

The point that I'm trying to make about indicator vs tab is user experience, users wouldn't want to have to slide 3 times just to get to syndicate missions every time they want to get to syndicates, and if we make indicators tappable we'd have to make them bigger and at that point tabs would be better because they have indicator plus labels and only take up vertical space vs  your indicator that takes up more horizontal space.

Did that make sense?

**Comment by SlayerOrnstein** [comment]
> About the little circle next to name, it's just a marker for logo.

Technically speaking Navis doesn't have a logo, so you're good.

**Comment by SlayerOrnstein** [comment]
@TobiTenno @vanja-san

Apart from somethings here and there, I do like this design and I wouldn't mind adding a lot of this.

**Comment by vanja-san** [comment]
@SlayerOrnstein Okay, I heard you. I'm going to try and craft something for tabs now. 😌👌

**Comment by vanja-san** [comment]
@SlayerOrnstein Here's one option (tabs-slide):
<img src="https://user-images.githubusercontent.com/7201687/152667144-821cd0bf-4d88-4de9-b2bd-d53a219272ea.png" width=35%>

ℹ️ Such tabs will be handy for other localization languages.

Highlighted tab:
<img src="https://user-images.githubusercontent.com/7201687/152667520-c9acd1d1-8f28-4424-bda0-db69a6438a82.png" width=35%> OR <img src="https://user-images.githubusercontent.com/7201687/152667553-62c4ef82-61c1-46a7-bdd4-7202909b9cf8.png" width=35%>

**Comment by vanja-san** [comment]
Let me tell you right away, the icons were taken from the Material Design site!

**Comment by SlayerOrnstein** [comment]
> Let me tell you right away, icons were taken from Material Design site!

We use flutter, I know they also use material design icons from there, but if you wanna take a closer look https://api.flutter.dev/flutter/material/Icons-class.html

> @SlayerOrnstein Here's one option (tabs-slide): ℹ️ Such tabs will be handy for other localization languages. Highlighted tab: <img alt="" width="35%" src="https://user-images.githubusercontent.com/7201687/152667520-c9acd1d1-8f28-4424-bda0-db69a6438a82.png">ℹ️ or <img alt="" width="35%" src="https://user-images.githubusercontent.com/7201687/152667760-d149d87b-5ed2-4845-ac7e-549394ec5492.png">ℹ️
> 
> Or in case: <img alt="" width="35%" src="https://user-images.githubusercontent.com/7201687/152668023-e18aa453-f2af-4589-adff-bc403e59fb26.png">

trying to decided which one is closer to spec, since it only says that I *can* have it flushed with the appbar but nothing about not doing it.

**Comment by vanja-san** [comment]
Choice is yours, my job is to suggest a few ideas. 😌

**Comment by vanja-san** [comment]
Is there an option to use "rounded" icons there?

**Comment by SlayerOrnstein** [comment]
> @SlayerOrnstein
> Will you be able to choose the icons of your choice?

Yeah I should be able to as long as it's there.

> Choice is yours, my job is to suggest a few ideas. 😌

Will more then likely start implementing bit by bit in the morning this in the morning.

Was really interested in the "exploring" section because it covered how I would add the maps and fishing data so I'm pretty eager about it. Do send me links to the Baro image you were using and any other specs about the cards, I will probably keep the discord button in the about tile so don't worry to much about that.

Note:
Because I haven't figured out to properly plot the map dynamically it's more the likely that I'll keep the Map icons as links for the time being.

**Comment by vanja-san** [comment]
<details>
  <summary>Images</summary>
  
  ![изображение](https://user-images.githubusercontent.com/7201687/152669173-0c5817e8-19ac-4431-9a9c-ec3d825e3287.png)

Plains of Eidolon
![изображение](https://user-images.githubusercontent.com/7201687/152669348-ed8a5dcb-61fd-4411-b228-f7557671beb4.png)

Vallis Orb
![изображение](https://user-images.githubusercontent.com/7201687/152669855-a5b7ccf2-9567-4937-8eeb-548f5265c14f.png)

</details>

**Comment by SlayerOrnstein** [comment]
@vanja-san just to let you know #114 creates dev builds that you can use to check the progress and voice concerns

**Comment by SlayerOrnstein** [comment]
Trying to reuse what we already have with the general concept.

![Screenshot_20220219-191346_Navis~2.png](https://user-images.githubusercontent.com/6075693/154823569-5cc928ff-1087-4904-b93e-c4c48c176a3e.png)

![Screenshot_20220219-191308_Navis~2.png](https://user-images.githubusercontent.com/6075693/154823574-d46698db-ae27-4076-9436-6777734d6725.png)

Note:
Obviously these aren't real timings and the information was manipulated to show the different states.

**Comment by SlayerOrnstein** [comment]
Since construction progress isn't as high priority to players, what are your thoughts about making the widget more compact and putting it under invasions?

![Screenshot_1646616578](https://user-images.githubusercontent.com/6075693/156952975-5a347cd0-c9e0-4aba-8990-68ca36525920.png)

![Screenshot_1646616511](https://user-images.githubusercontent.com/6075693/156952978-3226d985-791f-4bb5-b34f-c2ba858d896b.png)

**Comment by vanja-san** [comment]
@SlayerOrnstein That's probably where he belongs.

**Comment by SlayerOrnstein** [comment]
@vanja-san but does the compact style work for everyone?

**Comment by TobiTenno** [comment]
i like the look of that. it's a little confusing that it's under invasions, personally.... thinking about it more it makes sense since that's what drives it up, i just dunno if that's clear to everyone.

**Comment by SlayerOrnstein** [comment]
> i like the look of that. it's a little confusing that it's under invasions, personally.... thinking about it more it makes sense since that's what drives it up, i just dunno if that's clear to everyone.

Then I'll sleep on a title. There's more then enough space for one .
